name: 'Triggers playlist update and upload workflow'

on:
  push:
    branch:
      debug-dup
      
jobs:
  Upload_Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute Program
        run: ./triggerRun.sh ${{ vars.PLAYLIST_ONE }}