name: 'Upload Episode from YouTube To Anchor.Fm'

on:
  push:
    branches: 
      - main

# TODO: See if the checkout will be of correct commit or not
jobs:
  Upload_Action:
    runs-on: ubuntu-latest
    needs: Extract_episode
    steps:
      - uses: actions/checkout@v3
        run: |
          echo "Video ID to be converted" && \
          cat episode.json

      - name: Upload Episode from YouTube To Anchor.Fm
        uses: Schrodinger-Hat/youtube-to-anchorfm@v2.0.0
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: /github/workspace
          SAVE_AS_DRAFT: true # Remove before handover
          LOAD_THUMBNAIL: true # Remove if thumbnail is not required as episode art
          SET_PUBLISH_DATE: true # Sets publishing date 